# https://dahianlamindakide.ayriyazilir.com/

language: node_js
node_js:
  - '4' # LTS
  - '6' # Latest

sudo: required
dist: trusty

git:
  depth: 1

addons:
  hosts:
  - dahianlamindakide.ayriyazilir.com

env:
  - NODE_ENV=development

before_install:
  # Install apt packages
  - sudo apt-get -qq update 
  - sudo apt-get install -y chromium-browser
  - sudo apt-get install -y libnotify-bin # gulp-notify
  - sudo apt-get install -y nmap

  # Install global npm packages
  - npm install -g npm
  - npm install -g bower
  - npm install -g codeceptjs
  - npm install -g gulp
  - npm install -g http-server
  - npm install -g webdriverio

  # Install local npm packages
  - npm install
  - npm link webdriverio

  # Install Linuxbrew
  - echo -ne '\n' | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)" 
  - PATH="$HOME/.linuxbrew/bin:$PATH"
  - echo 'export PATH="$HOME/.linuxbrew/bin:$PATH"' >> ~/.bash_profile
  - source ~/.bash_profile
  - brew update && brew upgrade

  # Install Selenium server and browser drivers
  - brew install selenium-server-standalone
  - brew install chromedriver && chromedriver --version
  # - brew install geckodriver && geckodriver --version

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - "selenium-server -port 4444 >/dev/null 2>&1 &"
  - sleep 5
  - nmap -p 4444 127.0.0.1
  - "npm start >/dev/null 2>&1 &"
  - sleep 5
  - nmap -p 6869 127.0.0.1

script:
  - npm run test-chrome
